### ISSUE TITLE
Setup script can't download the model

### ISSUE THREAD

**Issue by orcinus** [jankais3r/Video-Depthify#1]
This part of the colaboratory setup script:

```
!gdown https://drive.google.com/uc?id=1nqW_Hwj86kslfsXR7EnXpEWdO2csz1cC
```

Returns:

```
Permission denied: https://drive.google.com/0/uc?id=1nqW_Hwj86kslfsXR7EnXpEWdO2csz1cC
Maybe you need to change permission over 'Anyone with the link'?
```

Oddly enough, i can download it just fine manually from google drive.
Any ideas?

**Comment by jankais3r** [comment]
Works for me. Probably was some temporary glitch.

![image](https://user-images.githubusercontent.com/2159464/125753437-5fd97549-c534-4122-908d-c942d4b70583.png)

**Comment by orcinus** [comment]
Yup, works fine now.
Strange.
Thanks for looking into it!
