### ISSUE TITLE
Optimal setup to run this

### ISSUE THREAD

**Issue by netgfx** [jankais3r/Video-Depthify#5]
Hello,

What would you say is the optimal setup for this work? Better CPU, RAM, GPU? We processed a small video and it took approximately 2 hours to produce the depth map, but the machine we run it was pretty low in capabilities. So we were wondering what is the recommended or optimal setup for this script to run as efficiently as possible.

Thanks!

**Comment by wcapes** [comment]
I would recommend install CUDA (https://medium.com/@jjlovesstudying/python-cuda-set-up-on-windows-10-for-gpu-support-78126284b085) and getting a good GFX card for better performance.

I have a GeForce 1660 Super and it's acceptable, but not fast - so get a better card
